# Generated by Django 5.2.17 on 2026-09-23 01:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_file', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('employability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profile_completed', models.BooleanField(default=False)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_id', models.IntegerField()),
                ('applicant_id', models.IntegerField()),
                ('employer_id', models.IntegerField()),
                ('employability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feedback_message', models.TextField()),
                ('feedback_type', models.CharField(default='automatic', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'candidate_feedback',
            },
        ),
        migrations.CreateModel(
            name='CmsBrand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('brand_overlay_title', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_overlay_description', models.TextField(blank=True, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=500, null=True)),
                ('brand_category', models.CharField(default='cor', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_brands',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CmsHeroSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, default='Learn More', max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, default='#', max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cms_hero_slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CmsNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('news_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cms_news',
            },
        ),
        migrations.CreateModel(
            name='CmsSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_key', models.CharField(max_length=100, unique=True)),
                ('section_name', models.CharField(max_length=100)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('html', 'HTML'), ('image', 'Image'), ('gallery', 'Gallery'), ('slider', 'Slider')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cms_sections',
            },
        ),
        migrations.CreateModel(
            name='CmsTestimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'cms_testimonials',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(default='General Inquiry', max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_inquiries',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_website', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='MlFeatureImportance',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('importance_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ml_feature_importance',
            },
        ),
        migrations.CreateModel(
            name='MlModelPerformance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('precision_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recall_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('f1_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('training_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ml_model_performance',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks_history', models.TextField(blank=True, null=True)),
                ('applicant_remarks_history', models.TextField(blank=True, null=True)),
                ('reviewed_by_employer_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_file', models.CharField(blank=True, max_length=255, null=True)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.applicant')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='CandidateMlFeature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('skills_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('experience_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('education_match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('employability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_ml_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('extracted_features', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='app.application')),
            ],
            options={
                'db_table': 'candidate_ml_features',
            },
        ),
        migrations.CreateModel(
            name='ChatbotRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommended_role', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('missing_skills', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
            ],
            options={
                'db_table': 'chatbot_recommendations',
            },
        ),
        migrations.CreateModel(
            name='CmsContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=100)),
                ('field_value', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app.cmssection')),
            ],
            options={
                'db_table': 'cms_content',
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interview_type', models.CharField(help_text='in-person, phone, video', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', help_text='scheduled, completed, cancelled, rescheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='app.application')),
                ('employer', models.ForeignKey(db_column='employer_id', on_delete=django.db.models.deletion.CASCADE, to='app.employer')),
            ],
            options={
                'db_table': 'interview_schedules',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('target_qualifications', models.TextField(blank=True, help_text='Comma-separated qualification IDs', null=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(db_column='employer_id', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='app.employer')),
            ],
            options={
                'db_table': 'job_postings',
            },
        ),
        migrations.CreateModel(
            name='CandidateRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
                ('employer', models.ForeignKey(db_column='employer_id', on_delete=django.db.models.deletion.CASCADE, to='app.employer')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='app.jobposting')),
            ],
            options={
                'db_table': 'candidate_recommendations',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.jobposting'),
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='app.jobposting')),
            ],
            options={
                'db_table': 'job_recommendations',
            },
        ),
        migrations.CreateModel(
            name='MlApplicationScreening',
            fields=[
                ('screening_id', models.AutoField(primary_key=True, serialize=False)),
                ('ml_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prediction_class', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('features_used', models.JSONField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='app.application')),
            ],
            options={
                'db_table': 'ml_application_screening',
            },
        ),
        migrations.CreateModel(
            name='JobQualificationMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='qualification_mappings', to='app.jobposting')),
                ('qualification', models.ForeignKey(db_column='qualification_id', on_delete=django.db.models.deletion.CASCADE, to='app.qualification')),
            ],
            options={
                'db_table': 'job_qualification_mapping',
            },
        ),
        migrations.CreateModel(
            name='ChatbotAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_number', models.IntegerField(default=1)),
                ('question_text', models.TextField(default='')),
                ('answer_text', models.TextField(default='')),
                ('answer_value', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='general', max_length=255)),
                ('score_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
                ('qualification', models.ForeignKey(blank=True, db_column='qualification_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.qualification')),
            ],
            options={
                'db_table': 'chatbot_answers',
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_file', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('skills_extracted', models.TextField(blank=True, null=True)),
                ('education_extracted', models.TextField(blank=True, null=True)),
                ('experience_extracted', models.TextField(blank=True, null=True)),
                ('qualifications_extracted', models.TextField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
            ],
            options={
                'db_table': 'resume_analysis',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(db_column='applicant_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='app.applicant')),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_applicants', to='app.jobposting')),
            ],
            options={
                'db_table': 'saved_jobs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('application', 'Application'), ('recommendation', 'Recommendation'), ('system', 'System'), ('job_update', 'Job Update')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.user')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.user')),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='app.user')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_id', models.IntegerField(blank=True, null=True)),
                ('feedback_type', models.CharField(max_length=50)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='app.user'),
        ),
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_text', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_sent', models.BooleanField(default=False)),
                ('inquiry', models.ForeignKey(db_column='inquiry_id', on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.contactinquiry')),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
            options={
                'db_table': 'contact_replies',
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=100)),
                ('action_description', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'audit_trail',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to='app.user'),
        ),
    ]
