# Generated by Django 5.2.17 on 2026-10-03 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employer_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='admin_qualification',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_status',
            field=models.CharField(choices=[('for_review', 'For Review'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('for_interview', 'For Interview'), ('interview_completed', 'Interview Completed'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='for_review', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='forwarded_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_applications', to='app.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='forwarded_to_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interview_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='positions_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to='app.user'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='special_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='urgency',
            field=models.CharField(blank=True, default='Normal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Review'), ('forwarded', 'Forwarded to Employer'), ('for_review', 'For Employer Review'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('for_interview', 'For Interview'), ('interviewed', 'Interviewed'), ('interview_completed', 'Interview Completed'), ('accepted', 'Hired / Accepted'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_type',
            field=models.CharField(default='Online', help_text='Online, In-person, phone, video', max_length=50),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active / Posted'), ('closed', 'Closed'), ('draft', 'Draft')], default='pending', max_length=20),
        ),
    ]
