# Generated by Django 5.2.17 on 2026-10-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employer_candidate_notifications'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactinquiry',
            index=models.Index(fields=['is_read'], name='inquiry_read_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read'], name='msg_receiver_read_idx'),
        ),
    ]
