from django.urls import path, re_path
from app.views import (
    views_public, views_auth, views_applicant,
    views_employer, views_admin, views_chat
)

urlpatterns = [
    # ── Public Pages ──
    path('', views_public.index_view, name='index'),
    re_path(r'^(?:frontend/)?index\.php$', views_public.index_view),
    path('about/', views_public.about_view, name='about'),
    re_path(r'^(?:frontend/)?about\.php$', views_public.about_view),
    path('services/', views_public.services_view, name='services'),
    re_path(r'^(?:frontend/)?services\.php$', views_public.services_view),
    path('solutions/', views_public.solutions_view, name='solutions'),
    re_path(r'^(?:frontend/)?solutions\.php$', views_public.solutions_view),
    path('printmanagement/', views_public.printmanagement_view, name='printmanagement'),
    re_path(r'^(?:frontend/)?printmanagement\.php$', views_public.printmanagement_view),
    path('computingproducts/', views_public.computingproducts_view, name='computingproducts'),
    re_path(r'^(?:frontend/)?computingproducts\.php$', views_public.computingproducts_view),
    path('retailsolutions/', views_public.retailsolutions_view, name='retailsolutions'),
    re_path(r'^(?:frontend/)?retailsolutions\.php$', views_public.retailsolutions_view),
    path('audiovisual/', views_public.audiovisual_view, name='audiovisual'),
    re_path(r'^(?:frontend/)?audiovisual\.php$', views_public.audiovisual_view),
    path('informationmanagement/', views_public.informationmanagement_view, name='informationmanagement'),
    re_path(r'^(?:frontend/)?informationmanagement\.php$', views_public.informationmanagement_view),
    path('businessautomation/', views_public.businessautomation_view, name='businessautomation'),
    re_path(r'^(?:frontend/)?businessautomation\.php$', views_public.businessautomation_view),
    path('cybersecurity/', views_public.cybersecurity_view, name='cybersecurity'),
    re_path(r'^(?:frontend/)?cybersecurity\.php$', views_public.cybersecurity_view),
    path('hp/', views_public.hp_view, name='hp'),
    re_path(r'^(?:frontend/)?hp\.php$', views_public.hp_view),
    re_path(r'^(?:frontend/)?news\.php$', views_public.news_view, name='news'),
    path('careers/', views_public.careers_view, name='careers'),
    path('jobs/', views_public.careers_view, name='jobs'),
    re_path(r'^(?:frontend/)?(?:careers|jobs)\.php$', views_public.careers_view),
    re_path(r'^(?:frontend/)?job_details_public\.php$', views_public.job_details_public_view),
    path('job/<int:job_id>/', views_public.job_details_public_view, name='job_details_public'),
    re_path(r'^(?:frontend/)?news_details\.php$', views_public.news_details_view, name='news_details'),
    path('contact/', views_public.contactus_view, name='contact'),
    path('contactus/', views_public.contactus_view, name='contactus'),
    re_path(r'^(?:frontend/)?contact(?:us)?\.php$', views_public.contactus_view),
    re_path(r'^(?:frontend/)?(?:includes/handlers/)?contact_handler\.php$', views_public.contact_handler_view),

    # ── Private Applicant Documents ──
    path('resume/applicant/<int:applicant_id>/', views_public.applicant_resume_view, name='applicant_resume'),
    path('resume/application/<int:application_id>/', views_public.application_resume_view, name='application_resume'),

    # ── Authentication & Session ──
    path('login/', views_auth.login_register_view, name='login'),
    path('register/', views_auth.login_register_view, name='register'),
    re_path(r'^(?:frontend/)?loginregister\.php$', views_auth.login_register_view),
    path('logout/', views_auth.logout_view, name='logout'),
    re_path(r'^(?:frontend/)?includes/auth/logout\.php$', views_auth.logout_view),
    re_path(r'^(?:frontend/)?send_otp\.php$', views_auth.send_otp_view),
    re_path(r'^(?:frontend/)?verify_otp\.php$', views_auth.verify_otp_view),
    re_path(r'^(?:frontend/)?includes/auth/check_session\.php$', views_auth.check_session_api),

    # ── Applicant Portal ──
    path('applicant/dashboard/', views_applicant.dashboard_view, name='applicant_dashboard'),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Dd]ashboard(?:\.php|/)?$', views_applicant.dashboard_view),
    path('applicant/jobs/', views_applicant.jobs_view, name='applicant_jobs'),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Jj]obs(?:\.php|/)?$', views_applicant.jobs_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Jj]ob_details(?:\.php|/)?$', views_applicant.job_details_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Aa]pply_job(?:\.php|/)?$', views_applicant.apply_job_view),
    path('applicant/applications/', views_applicant.applications_view, name='applicant_applications'),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Aa]pplications(?:\.php|/)?$', views_applicant.applications_view),
    path('applicant/profile/', views_applicant.profile_view, name='applicant_profile'),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Pp]rofile(?:\.php|/)?$', views_applicant.profile_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Ss]ave_job(?:\.php|/)?$', views_applicant.save_job_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Cc]hatbot(?:\.php|/)?$', views_applicant.chatbot_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Cc]hatbot_handler(?:\.php|/)?$', views_applicant.chatbot_handler_api),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Uu]pdate_application(?:\.php|/)?$', views_applicant.update_application_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Ee]mployer(?:\.php|/)?$', views_applicant.employer_view),
    re_path(r'^(?:frontend/)?(?:applicant/)?[Cc]hat(?:\.php|/)?$', views_chat.chat_view),

    # ── Employer Portal ──
    path('employer/dashboard/', views_employer.dashboard_view, name='employer_dashboard'),
    re_path(r'^(?:frontend/)?employer/dashboard\.php$', views_employer.dashboard_view),
    path('employer/request_talent/', views_employer.request_talent_view, name='employer_request_talent'),
    re_path(r'^(?:frontend/)?employer/request_talent\.php$', views_employer.request_talent_view),
    path('employer/post_job/', views_employer.post_job_view, name='employer_post_job'),
    re_path(r'^(?:frontend/)?employer/post_job\.php$', views_employer.post_job_view),
    path('employer/jobs/', views_employer.jobs_view, name='employer_jobs'),
    re_path(r'^(?:frontend/)?employer/jobs\.php$', views_employer.jobs_view),
    re_path(r'^(?:frontend/)?employer/edit_job\.php$', views_employer.edit_job_view),
    path('employer/candidates/', views_employer.candidates_view, name='employer_candidates'),
    re_path(r'^(?:frontend/)?employer/candidates\.php$', views_employer.candidates_view),
    re_path(r'^(?:frontend/)?includes/ml/candidate_ranking\.php$', views_employer.candidates_view),
    path('employer/recommended_candidates/', views_employer.recommended_candidates_view, name='employer_recommended_candidates'),
    re_path(r'^(?:frontend/)?employer/recommended_candidates\.php$', views_employer.recommended_candidates_view),
    re_path(r'^(?:frontend/)?employer/view_candidate\.php$', views_employer.view_candidate_view),
    re_path(r'^(?:frontend/)?employer/update_status\.php$', views_employer.update_status_api),
    path('employer/schedule_interview_api/', views_employer.schedule_interview_api, name='employer_schedule_interview_api'),
    re_path(r'^(?:frontend/)?employer/schedule_interview\.php$', views_employer.schedule_interview_api),
    re_path(r'^(?:frontend/)?employer/chatbot_review\.php$', views_employer.chatbot_review_view),
    re_path(r'^(?:frontend/)?employer/chat\.php$', views_chat.chat_view),

    # ── Admin Portal ──
    path('admin/dashboard/', views_admin.dashboard_view, name='admin_dashboard'),
    re_path(r'^(?:frontend/)?admin/dashboard\.php$', views_admin.dashboard_view),
    path('admin/users/', views_admin.users_view, name='admin_users'),
    re_path(r'^(?:frontend/)?admin/users\.php$', views_admin.users_view),
    path('admin/post_job/', views_admin.post_job_view, name='admin_post_job'),
    re_path(r'^(?:frontend/)?admin/post_job\.php$', views_admin.post_job_view),
    path('admin/jobs/', views_admin.jobs_view, name='admin_jobs'),
    re_path(r'^(?:frontend/)?admin/jobs\.php$', views_admin.jobs_view),
    path('admin/job_request_action/', views_admin.job_request_action_api, name='admin_job_request_action'),
    re_path(r'^(?:frontend/)?admin/job_request_action\.php$', views_admin.job_request_action_api),
    path('admin/forward_candidate/', views_admin.forward_candidate_api, name='admin_forward_candidate'),
    re_path(r'^(?:frontend/)?admin/forward_candidate\.php$', views_admin.forward_candidate_api),
    path('admin/batch_forward_candidates/', views_admin.batch_forward_candidates_api, name='admin_batch_forward_candidates'),
    re_path(r'^(?:frontend/)?admin/batch_forward_candidates\.php$', views_admin.batch_forward_candidates_api),
    path('admin/jobs/<int:job_id>/candidates/', views_admin.job_candidates_view, name='admin_job_candidates'),
    path('admin/jobs/<int:job_id>/export_excel/', views_admin.export_candidates_excel_view, name='admin_export_candidates_excel'),
    path('admin/jobs/<int:job_id>/upload_google_drive/', views_admin.upload_candidates_google_drive_api, name='admin_upload_candidates_google_drive'),
    path('admin/jobs/<int:job_id>/export_csv/', views_admin.export_candidates_csv_view, name='admin_export_candidates_csv'),
    path('admin/jobs/<int:job_id>/notify_qualified/', views_admin.notify_qualified_applicants_view, name='admin_notify_qualified_applicants'),
    path('admin/jobs/<int:job_id>/forward_qualified/', views_admin.forward_qualified_candidates_view, name='admin_forward_qualified_candidates'),
    path('admin/notify_applicant/<int:application_id>/', views_admin.notify_single_applicant_view, name='admin_notify_single_applicant'),
    path('admin/upload_candidates_google_drive/', views_admin.upload_candidates_google_drive_api, name='admin_upload_candidates_gdrive'),
    re_path(r'^(?:frontend/)?admin/upload_candidates_google_drive\.php$', views_admin.upload_candidates_google_drive_api),
    re_path(r'^(?:frontend/)?admin/export_candidates_excel\.php$', views_admin.export_candidates_excel_view),
    re_path(r'^(?:frontend/)?admin/export_candidates_csv\.php$', views_admin.export_candidates_csv_view),
    path('admin/edit_job/<int:job_id>/', views_admin.edit_job_view, name='admin_edit_job'),
    re_path(r'^(?:frontend/)?admin/edit_job\.php$', views_admin.edit_job_view),
    path('admin/candidates/', views_admin.candidates_view, name='admin_candidates'),
    re_path(r'^(?:frontend/)?admin/candidates\.php$', views_admin.candidates_view),
    path('admin/candidates/<int:application_id>/', views_admin.view_candidate_view, name='admin_view_candidate'),
    re_path(r'^(?:frontend/)?admin/view_candidate\.php$', views_admin.view_candidate_view),
    re_path(r'^(?:frontend/)?admin/update_status\.php$', views_admin.update_status_api),
    path('admin/analytics/', views_admin.analytics_view, name='admin_analytics'),
    re_path(r'^(?:frontend/)?admin/analytics\.php$', views_admin.analytics_view),
    path('admin/cms/', views_admin.cms_view, name='admin_cms'),
    re_path(r'^(?:frontend/)?admin/cms\.php$', views_admin.cms_view),
    path('admin/messages/', views_admin.messages_view, name='admin_messages'),
    re_path(r'^(?:frontend/)?admin/messages\.php$', views_admin.messages_view),
    path('admin/inquiries/', views_admin.messages_view, name='admin_inquiries'),
    re_path(r'^(?:frontend/)?admin/inquiries\.php$', views_admin.messages_view),
    re_path(r'^(?:frontend/)?admin/contact_api\.php$', views_admin.contact_api_view),
    path('admin/audit_trail/', views_admin.audit_trail_view, name='admin_audit_trail'),
    re_path(r'^(?:frontend/)?admin/audit_trail\.php$', views_admin.audit_trail_view),
    re_path(r'^(?:frontend/)?admin/chatbot_review\.php$', views_admin.chatbot_review_view),
    re_path(r'^(?:frontend/)?admin/chat\.php$', views_chat.chat_view),

    # ── Messages API ──
    re_path(r'^(?:frontend/)?includes/handlers/message_handler\.php$', views_chat.message_handler_api),
]
