from django.urls import path, re_path
from app.views import (
    views_public, views_auth, views_applicant,
    views_employer, views_admin, views_chat
)

urlpatterns = [
    # ── Public Pages ──
    path('', views_public.index_view, name='index'),
    re_path(r'^(?:frontend/)?index\.php$', views_public.index_view),
    path('about/', views_public.about_view, name='about'),
    re_path(r'^(?:frontend/)?about\.php$', views_public.about_view),
    path('services/', views_public.services_view, name='services'),
    re_path(r'^(?:frontend/)?services\.php$', views_public.services_view),
    path('solutions/', views_public.solutions_view, name='solutions'),
    re_path(r'^(?:frontend/)?solutions\.php$', views_public.solutions_view),
    re_path(r'^(?:frontend/)?news\.php$', views_public.news_view, name='news'),
    path('careers/', views_public.careers_view, name='careers'),
    path('jobs/', views_public.careers_view, name='jobs'),
    re_path(r'^(?:frontend/)?(?:careers|jobs)\.php$', views_public.careers_view),
    re_path(r'^(?:frontend/)?job_details_public\.php$', views_public.job_details_public_view),
    path('job/<int:job_id>/', views_public.job_details_public_view, name='job_details_public'),
    re_path(r'^(?:frontend/)?news_details\.php$', views_public.news_details_view, name='news_details'),
    re_path(r'^(?:frontend/)?(?:includes/handlers/)?contact_handler\.php$', views_public.contact_handler_view),

    # ── Authentication & Session ──
    path('login/', views_auth.login_register_view, name='login'),
    path('register/', views_auth.login_register_view, name='register'),
    re_path(r'^(?:frontend/)?loginregister\.php$', views_auth.login_register_view),
    path('logout/', views_auth.logout_view, name='logout'),
    re_path(r'^(?:frontend/)?includes/auth/logout\.php$', views_auth.logout_view),
    re_path(r'^(?:frontend/)?send_otp\.php$', views_auth.send_otp_view),
    re_path(r'^(?:frontend/)?verify_otp\.php$', views_auth.verify_otp_view),
    re_path(r'^(?:frontend/)?includes/auth/check_session\.php$', views_auth.check_session_api),

    # ── Applicant Portal ──
    path('applicant/dashboard/', views_applicant.dashboard_view, name='applicant_dashboard'),
    re_path(r'^(?:frontend/)?applicant/dashboard\.php$', views_applicant.dashboard_view),
    path('applicant/jobs/', views_applicant.jobs_view, name='applicant_jobs'),
    re_path(r'^(?:frontend/)?applicant/jobs\.php$', views_applicant.jobs_view),
    re_path(r'^(?:frontend/)?applicant/job_details\.php$', views_applicant.job_details_view),
    re_path(r'^(?:frontend/)?applicant/apply_job\.php$', views_applicant.apply_job_view),
    path('applicant/applications/', views_applicant.applications_view, name='applicant_applications'),
    re_path(r'^(?:frontend/)?applicant/applications\.php$', views_applicant.applications_view),
    path('applicant/profile/', views_applicant.profile_view, name='applicant_profile'),
    re_path(r'^(?:frontend/)?applicant/profile\.php$', views_applicant.profile_view),
    re_path(r'^(?:frontend/)?applicant/save_job\.php$', views_applicant.save_job_view),
    re_path(r'^(?:frontend/)?applicant/chatbot\.php$', views_applicant.chatbot_view),
    re_path(r'^(?:frontend/)?applicant/chatbot_handler\.php$', views_applicant.chatbot_handler_api),
    re_path(r'^(?:frontend/)?applicant/update_application\.php$', views_applicant.update_application_view),
    re_path(r'^(?:frontend/)?applicant/employer\.php$', views_applicant.employer_view),
    re_path(r'^(?:frontend/)?applicant/chat\.php$', views_chat.chat_view),

    # ── Employer Portal ──
    path('employer/dashboard/', views_employer.dashboard_view, name='employer_dashboard'),
    re_path(r'^(?:frontend/)?employer/dashboard\.php$', views_employer.dashboard_view),
    path('employer/request_talent/', views_employer.request_talent_view, name='employer_request_talent'),
    re_path(r'^(?:frontend/)?employer/request_talent\.php$', views_employer.request_talent_view),
    path('employer/post_job/', views_employer.post_job_view, name='employer_post_job'),
    re_path(r'^(?:frontend/)?employer/post_job\.php$', views_employer.post_job_view),
    path('employer/jobs/', views_employer.jobs_view, name='employer_jobs'),
    re_path(r'^(?:frontend/)?employer/jobs\.php$', views_employer.jobs_view),
    re_path(r'^(?:frontend/)?employer/edit_job\.php$', views_employer.edit_job_view),
    path('employer/candidates/', views_employer.candidates_view, name='employer_candidates'),
    re_path(r'^(?:frontend/)?employer/candidates\.php$', views_employer.candidates_view),
    re_path(r'^(?:frontend/)?includes/ml/candidate_ranking\.php$', views_employer.candidates_view),
    path('employer/recommended_candidates/', views_employer.recommended_candidates_view, name='employer_recommended_candidates'),
    re_path(r'^(?:frontend/)?employer/recommended_candidates\.php$', views_employer.recommended_candidates_view),
    re_path(r'^(?:frontend/)?employer/view_candidate\.php$', views_employer.view_candidate_view),
    re_path(r'^(?:frontend/)?employer/update_status\.php$', views_employer.update_status_api),
    re_path(r'^(?:frontend/)?employer/chatbot_review\.php$', views_employer.chatbot_review_view),
    re_path(r'^(?:frontend/)?employer/chat\.php$', views_chat.chat_view),

    # ── Admin Portal ──
    path('admin/dashboard/', views_admin.dashboard_view, name='admin_dashboard'),
    re_path(r'^(?:frontend/)?admin/dashboard\.php$', views_admin.dashboard_view),
    path('admin/users/', views_admin.users_view, name='admin_users'),
    re_path(r'^(?:frontend/)?admin/users\.php$', views_admin.users_view),
    path('admin/post_job/', views_admin.post_job_view, name='admin_post_job'),
    re_path(r'^(?:frontend/)?admin/post_job\.php$', views_admin.post_job_view),
    path('admin/jobs/', views_admin.jobs_view, name='admin_jobs'),
    re_path(r'^(?:frontend/)?admin/jobs\.php$', views_admin.jobs_view),
    path('admin/jobs/<int:job_id>/candidates/', views_admin.job_candidates_view, name='admin_job_candidates'),
    path('admin/edit_job/<int:job_id>/', views_admin.edit_job_view, name='admin_edit_job'),
    re_path(r'^(?:frontend/)?admin/edit_job\.php$', views_admin.edit_job_view),
    path('admin/candidates/', views_admin.candidates_view, name='admin_candidates'),
    re_path(r'^(?:frontend/)?admin/candidates\.php$', views_admin.candidates_view),
    path('admin/candidates/<int:application_id>/', views_admin.view_candidate_view, name='admin_view_candidate'),
    re_path(r'^(?:frontend/)?admin/view_candidate\.php$', views_admin.view_candidate_view),
    re_path(r'^(?:frontend/)?admin/update_status\.php$', views_admin.update_status_api),
    path('admin/analytics/', views_admin.analytics_view, name='admin_analytics'),
    re_path(r'^(?:frontend/)?admin/analytics\.php$', views_admin.analytics_view),
    path('admin/cms/', views_admin.cms_view, name='admin_cms'),
    re_path(r'^(?:frontend/)?admin/cms\.php$', views_admin.cms_view),
    path('admin/messages/', views_admin.messages_view, name='admin_messages'),
    re_path(r'^(?:frontend/)?admin/messages\.php$', views_admin.messages_view),
    re_path(r'^(?:frontend/)?admin/contact_api\.php$', views_admin.contact_api_view),
    path('admin/audit_trail/', views_admin.audit_trail_view, name='admin_audit_trail'),
    re_path(r'^(?:frontend/)?admin/audit_trail\.php$', views_admin.audit_trail_view),
    re_path(r'^(?:frontend/)?admin/chatbot_review\.php$', views_admin.chatbot_review_view),
    re_path(r'^(?:frontend/)?admin/chat\.php$', views_chat.chat_view),

    # ── Messages API ──
    re_path(r'^(?:frontend/)?includes/handlers/message_handler\.php$', views_chat.message_handler_api),
]
